Add guidelines on git branch naming
mullvad/coding-guidelines pull request #22
Opened 2024-04-18 14:58 UTC by faern

Nothing too controversial here I hope. But instead of transferring this information word of mouth it might be much simpler to have it written in a single place. Reduce risk of misunderstanding, and acts as a single source of truth in disputes.

Most of this is what we already do. Some of them are descriptions and arguments I came up with, but that I think you will find reasonable.

Just because I say slashes are allowed, that does not mean I suggest we should introduce them ASAP. I just want the guideline to be clear that they are allowed if a team would like to explore that area (I know we use them to some extent already)

2024-04-18 15:30 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/22#-:-Nvlp4LvBq2gjN33xGRi:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @albin-mullvad, @pinkisemils, and @raksooo)



<!-- Sent from Reviewable.io -->

2024-04-19 06:30 UTC, raksooo requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/22)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @faern, @pinkisemils, and @raksooo)

___
*[`README.md` line 168 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/22#-Nvp1kFvEu8cJoozpyxC:-Nvp1kFvEu8cJoozpyxD:b-96ibar) ([raw file](https://github.com/mullvad/coding-guidelines/blob/4049ca4781d9adc3ade9f35161deed68b1d9eec9/README.md#L168)):*
> ```Markdown
> * `suppress-CVE-2026-3872` - "CVE-2026-3872" is a unique identifier. Changing it could change its
>   meaning and/or make it less recognizable.
> * `fix-multicast-address-translation-IOS-123` - "DES-123" being a hypothetical ticketing system
> ```

The identifier should probably be the same in the branch name and the explanation.


<!-- Sent from Reviewable.io -->

2024-04-19 08:49 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/22)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @pinkisemils, and @raksooo)

___
*[`README.md` line 168 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/22#-Nvp1kFvEu8cJoozpyxC:-NvpXweZ9blGV82b7_nk:b-f2dqyq) ([raw file](https://github.com/mullvad/coding-guidelines/blob/4049ca4781d9adc3ade9f35161deed68b1d9eec9/README.md#L168)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The identifier should probably be the same in the branch name and the explanation.
</blockquote></details>

Well spotted. Fixed


<!-- Sent from Reviewable.io -->

2024-04-19 09:01 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/22)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @raksooo)

___
*[`README.md` line 168 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/22#-Nvp1kFvEu8cJoozpyxC:-Nvp_XL-3IMhw17oRkxS:b90ascx) ([raw file](https://github.com/mullvad/coding-guidelines/blob/4049ca4781d9adc3ade9f35161deed68b1d9eec9/README.md#L168)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Well spotted. Fixed
</blockquote></details>

 Can we make affordances for having the identifier be the prefix and not the suffix of the branch name?


<!-- Sent from Reviewable.io -->

2024-04-19 09:07 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/22)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @raksooo)

___
*[`README.md` line 168 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/22#-Nvp1kFvEu8cJoozpyxC:-Nvpam7-5ifU01lkjpwt:b-nbqsay) ([raw file](https://github.com/mullvad/coding-guidelines/blob/4049ca4781d9adc3ade9f35161deed68b1d9eec9/README.md#L168)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Can we make affordances for having the identifier be the prefix and not the suffix of the branch name?
</blockquote></details>

The guidelines say nothing about that. They do not forbid putting the identifier anywhere. This is just an example of legit reasons to sidestep kebab-casing (some automation needing a verbatim tag in the name).


<!-- Sent from Reviewable.io -->

2024-04-19 09:38 UTC, raksooo approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/22)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-19 09:42 UTC, merged