Add various things we discussed on all-hands meeting
mullvad/coding-guidelines pull request #4
Opened 2019-10-21 12:44 UTC by faern

I wrote this down as a result of what we discussed last week. Please read and give feedback. This highly affects the entire team, so important that everyone is on board with the changes/additions.

2019-10-21 13:26 UTC, mvd-ows approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-:-LriUkip-puvkcFEiSqp:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon, @jvff, @mvd-ows, @pinkisemils, and @pronebird)

___
*[README.md, line 86 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-LriUYvK-mm5IiD6mX5H:-LriUYvK-mm5IiD6mX5I:b-ft99lu) ([raw file](https://github.com/mullvad/coding-guidelines/blob/16c35401ab6c0fd7315ca67da03a57f79ae8f5a7/README.md#L86)):*
> ```Markdown
> 
> So for a given feature branch, there should generally not be "fix" commits fixing things from
> earlier commits in that same branch. The developer might experiment back and fourth with different
> ```

Wasn't going to say anything, but since you're updating this sentence, it's `back and forth`.


<!-- Sent from Reviewable.io -->

2019-10-21 13:53 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-:-LriXKZf1cijuUuhaPnn:bg7igkv)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, @jvff, @mvd-ows, @pinkisemils, and @pronebird)

___
*[README.md, line 85 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-LriYQ5S3zPcMFPgrw9J:-LriYQ5S3zPcMFPgrw9K:b69nx36) ([raw file](https://github.com/mullvad/coding-guidelines/blob/16c35401ab6c0fd7315ca67da03a57f79ae8f5a7/README.md#L85)):*
> ```Markdown
> experimented to get there.
> 
> So for a given feature branch, there should generally not be "fix" commits fixing things from
> ```

It's not entirely clear how strictly this rule should be enforced. Could it explain that you're allowed to break it to some degree, if rebasing the changes takes an unreasonable amount of time?


<!-- Sent from Reviewable.io -->

2019-10-21 18:22 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faern, @jvff, @mvd-ows, @pinkisemils, and @pronebird)

___
*[README.md, line 86 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-LriUYvK-mm5IiD6mX5H:-LrjWNAi6b--WZCdnLCQ:b-n3nsd) ([raw file](https://github.com/mullvad/coding-guidelines/blob/16c35401ab6c0fd7315ca67da03a57f79ae8f5a7/README.md#L86)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Wasn't going to say anything, but since you're updating this sentence, it's `back and forth`.
</blockquote></details>

Oops :) Fixed.


<!-- Sent from Reviewable.io -->

2019-10-22 10:24 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern, @jvff, @mvd-ows, @pinkisemils, and @pronebird)

___
*[README.md, line 10 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-Lrmz28E6TzKTVFfK6Gw:-Lrmz28E6TzKTVFfK6Gx:bpk6rt) ([raw file](https://github.com/mullvad/coding-guidelines/blob/6aa440d4f509e269623757618c545eb430d7a97a/README.md#L10)):*
> ```Markdown
> 
> As a remote team, a lot of work is done by individuals without too much interaction.
> It is recommended to discuss solutions and problems early and often. And show code before it is
> ```

Showing the code before it's done sounds contradictory. 

I suppose that means that we should discuss draft or proof of concept work before spending time on producing production ready code.


<!-- Sent from Reviewable.io -->

2019-10-22 10:30 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, @jvff, @mvd-ows, @pinkisemils, and @pronebird)

___
*[README.md, line 85 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-LriYQ5S3zPcMFPgrw9J:-Lrn-Gid3VR8xUhY-1jW:bnvvjx8) ([raw file](https://github.com/mullvad/coding-guidelines/blob/16c35401ab6c0fd7315ca67da03a57f79ae8f5a7/README.md#L85)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It's not entirely clear how strictly this rule should be enforced. Could it explain that you're allowed to break it to some degree, if rebasing the changes takes an unreasonable amount of time?
</blockquote></details>

I'd say squash to one commit when it's hard to untangle commits history.


<!-- Sent from Reviewable.io -->

2019-10-22 10:32 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, @jvff, @pinkisemils, and @pronebird)



<!-- Sent from Reviewable.io -->

2019-10-22 14:25 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dlon, @jvff, @pinkisemils, and @pronebird)

___
*[README.md, line 85 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-LriYQ5S3zPcMFPgrw9J:-LrnqUZV2uZtWc89uKgk:b-wcqvka) ([raw file](https://github.com/mullvad/coding-guidelines/blob/16c35401ab6c0fd7315ca67da03a57f79ae8f5a7/README.md#L85)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I'd say squash to one commit when it's hard to untangle commits history.
</blockquote></details>

I agree. If rebasing is hard because multiple commits in the feature branch end up with conflicts during the rebase, then just squash before the rebase. It does not have to be squashed to a single commit. Sometimes it's enough to squash a few commits that were causing the conflict in order to just have a single, or fewer, conflicts during rebase.
___
*[README.md, line 10 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-Lrmz28E6TzKTVFfK6Gw:-Lrnp_7C2dNbVbbacsC3:b-b7ib45) ([raw file](https://github.com/mullvad/coding-guidelines/blob/6aa440d4f509e269623757618c545eb430d7a97a/README.md#L10)):*
Exactly. Discussing the problem and evaluate solutions together is the main point here. And then it says to show code *if relevant*. Since sometimes discussing solutions involve looking at half done code. Evaluating if an abstraction seems sane etc before it's implemented everywhere. People can show the start of their solutions before going through refactoring the entire app into using the new style/interface or whatever.

Do you have a proposal how to word it if you don't agree with the current wording? Maybe:

> Show proof of concept code to evaluate if the chosen abstraction seems correct before going through with major refactoring using it.

?


<!-- Sent from Reviewable.io -->

2019-10-23 08:58 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, @jvff, @pinkisemils, and @pronebird)

___
*[README.md, line 10 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-Lrmz28E6TzKTVFfK6Gw:-LrroFia7CUeByolz6el:b-wo823z) ([raw file](https://github.com/mullvad/coding-guidelines/blob/6aa440d4f509e269623757618c545eb430d7a97a/README.md#L10)):*
>Show proof of concept code to evaluate if the chosen abstraction seems correct before going through with major refactoring using it.

Sounds better


<!-- Sent from Reviewable.io -->

2019-10-24 06:56 UTC, mvd-ows approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faern, @jvff, @mvd-ows, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2019-10-24 13:43 UTC, jvff requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern, @jvff, @mvd-ows, and @pinkisemils)

___
*[README.md, line 45 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-Lry-5exEJnTtNxDSRYo:-Lry-5exEJnTtNxDSRYp:b-40zsoa) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7e05293a4c4d6eab700cabcc3823487ee18e0dfe/README.md#L45)):*
> ```Markdown
> This generally works out quite well. But there is some friction to reach the end results, and it
> takes time. Since we know from history that most UI changes will receive a fair amount of
> feedback and be reworked a couple of times, it is even more important to start gather feedback
> ```

I think there's a typo here. `start to gather` or maybe `start gathering`?


<!-- Sent from Reviewable.io -->

2019-10-25 08:01 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jvff, @mvd-ows, @pinkisemils, and @pronebird)

___
*[README.md, line 85 at r1](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-LriYQ5S3zPcMFPgrw9J:-Ls0vR9SD3L7Nir0Aa7e:b-5u6bc9) ([raw file](https://github.com/mullvad/coding-guidelines/blob/16c35401ab6c0fd7315ca67da03a57f79ae8f5a7/README.md#L85)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I agree. If rebasing is hard because multiple commits in the feature branch end up with conflicts during the rebase, then just squash before the rebase. It does not have to be squashed to a single commit. Sometimes it's enough to squash a few commits that were causing the conflict in order to just have a single, or fewer, conflicts during rebase.
</blockquote></details>

I now added to the section above that this is more best effort and something to strive for, but nothing that is super strict. The perfect git history does not exist and defining what to strive for is always going to be a pretty loose definition. That does not mean we should not care at all though. So this part of the document is more guidelines what to aim for, not exactly what has to be achieved. Is this better?
___
*[README.md, line 10 at r2](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-Lrmz28E6TzKTVFfK6Gw:-Ls0tHTZ9E30tmPfrfoA:b-896fix) ([raw file](https://github.com/mullvad/coding-guidelines/blob/6aa440d4f509e269623757618c545eb430d7a97a/README.md#L10)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

>Show proof of concept code to evaluate if the chosen abstraction seems correct before going through with major refactoring using it.

Sounds better
</blockquote></details>

Done.
___
*[README.md, line 45 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-Lry-5exEJnTtNxDSRYo:-Ls0tZzX5jXyDWG61ua0:b-896fix) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7e05293a4c4d6eab700cabcc3823487ee18e0dfe/README.md#L45)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think there's a typo here. `start to gather` or maybe `start gathering`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-25 09:02 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jvff, @mvd-ows, @pinkisemils, and @pronebird)

___
*[README.md, line 41 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-LrzMCc4-dpp2DiAix0n:-LrzMCc4-dpp2DiAix0o:b7m9p9e) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7e05293a4c4d6eab700cabcc3823487ee18e0dfe/README.md#L41)):*
I'd say this could be worded in a more prescriptive manner rather than stating the issues/friction points we have now and how we should be approaching them.

Something like 
> For UI design, we prefer to iterate quickly and agree upon the desgin before writing any code for it. This is to avoid double-work where the implemented design will need to be reworked after receiving feedback too late.


<!-- Sent from Reviewable.io -->

2019-10-25 09:38 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff and @pronebird)



<!-- Sent from Reviewable.io -->

2019-10-25 11:11 UTC, jvff approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2019-10-25 11:26 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pinkisemils and @pronebird)

___
*[README.md, line 41 at r3](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-LrzMCc4-dpp2DiAix0n:-Ls1eiylBGsgfkz6NjH_:bq9saj9) ([raw file](https://github.com/mullvad/coding-guidelines/blob/7e05293a4c4d6eab700cabcc3823487ee18e0dfe/README.md#L41)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'd say this could be worded in a more prescriptive manner rather than stating the issues/friction points we have now and how we should be approaching them.

Something like 
> For UI design, we prefer to iterate quickly and agree upon the desgin before writing any code for it. This is to avoid double-work where the implemented design will need to be reworked after receiving feedback too late.
</blockquote></details>

Great suggestion! I took your text and made very minor edits.


<!-- Sent from Reviewable.io -->

2019-10-25 11:28 UTC, jvff approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2019-10-25 11:48 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2019-10-25 11:49 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2019-10-25 11:49 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-25 11:49 UTC, pronebird approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-25 11:49 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4#-:-Ls1jzUzAqAJU3GwrQzL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-25 12:02 UTC, jvff approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-25 18:36 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/coding-guidelines/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-28 12:09 UTC, merged